services:
  searxng:
    image: searxng/searxng:2024.10.28-b176323e8
    container_name: searxng-instance
    ports:
      - "8080:8080"
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml
      - ./uwsgi.ini:/etc/searxng/uwsgi.ini
    working_dir: /etc/searxng 
